src/Entity/Proyecto.php
<?php

namespace App\Entity;

use App\Repository\ProyectoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProyectoRepository::class)
 */
class Proyecto
{
    public const PROYECTO_STATE = [
        'Enproceso' => 'enproceso',
        'Aprobado' => 'aprobado',
        'Terminado' => 'terminado'
    ];


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_entrega;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $estado;

    /**
     * @ORM\OneToOne(targetEntity=Presupuesto::class, inversedBy="proyecto", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $presupuesto;

    /**
     * @ORM\OneToMany(targetEntity=Tarea::class, mappedBy="proyecto", orphanRemoval=true)
     */
    private $tareas;

    public function __construct()
    {
        $this->tareas = new ArrayCollection();
        $this->estado = self::PROYECTO_STATE['Enproceso'];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFechaEntrega(): ?\DateTimeInterface
    {
        return $this->fecha_entrega;
    }

    public function setFechaEntrega(\DateTimeInterface $fecha_entrega): self
    {
        $this->fecha_entrega = $fecha_entrega;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        if(!in_array($estado, $this::PROYECTO_STATE)){
            throw new Exception('Tipo de presupuesto no válido: '.$estado);
        };
        $this->estado = $estado;

        return $this;
    }

    public function getPresupuesto(): ?Presupuesto
    {
        return $this->presupuesto;
    }

    public function setPresupuesto(Presupuesto $presupuesto): self
    {
        $this->presupuesto = $presupuesto;

        return $this;
    }

    /**
     * @return Collection<int, Tarea>
     */
    public function getTareas(): Collection
    {
        return $this->tareas;
    }

    public function addTarea(Tarea $tarea): self
    {
        if (!$this->tareas->contains($tarea)) {
            $this->tareas[] = $tarea;
            $tarea->setProyecto($this);
        }

        return $this;
    }

    public function removeTarea(Tarea $tarea): self
    {
        if ($this->tareas->removeElement($tarea)) {
            // set the owning side to null (unless already changed)
            if ($tarea->getProyecto() === $this) {
                $tarea->setProyecto(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return (string) ($this->getId() ?? '');
    }
}

src/Form/ProyectoType.php
<?php

namespace App\Form;

use App\Entity\Proyecto;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProyectoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('presupuesto')
            ->add('fecha_entrega', DateTimeType::class)
        ;

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            /** @var var Presupuesto $presupuesto */
            $proyecto = $event->getData();
            $form = $event->getForm();

            if(null !== $proyecto->getId()) {
                $form->add('estado', ChoiceType::class, [
                    'choices'  => Proyecto::PROYECTO_STATE
                ]);
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Proyecto::class,
        ]);
    }
}

src/Controller/ProyectoController.php
<?php

namespace App\Controller;

use App\Entity\Proyecto;
use App\Entity\Tarea;
use App\Event\Proyecto\ProyectoEvent;
use App\EventSubscriber\ProyectoEventSubscriber;
use App\Form\ProyectoType;
use App\Repository\ProyectoRepository;
use App\Services\EmailService;
use Psr\EventDispatcher\EventDispatcherInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/proyecto")
 * @Security("is_granted('ROLE_JEFEPROYECTO')")
 */
class ProyectoController extends AbstractController
{
    private EventDispatcherInterface $eventDispatcher;
    private EmailService $emailService;

    public function __construct(EventDispatcherInterface $eventDispatcher, EmailService $emailService)
    {
        $this->eventDispatcher = $eventDispatcher;
        $this->emailService = $emailService;
    }

    /**
     * @Route("/", name="app_proyecto_index", methods={"GET"})
     */
    public function index(ProyectoRepository $proyectoRepository): Response
    {
        return $this->render('proyecto/index.html.twig', [
            'proyectos' => $proyectoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_proyecto_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ProyectoRepository $proyectoRepository): Response
    {
        $proyecto = new Proyecto();
        $form = $this->createForm(ProyectoType::class, $proyecto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $proyectoRepository->add($proyecto);
            return $this->redirectToRoute('app_proyecto_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('proyecto/new.html.twig', [
            'proyecto' => $proyecto,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_proyecto_show", methods={"GET"})
     */
    public function show(Proyecto $proyecto): Response
    {
        return $this->render('proyecto/show.html.twig', [
            'proyecto' => $proyecto,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_proyecto_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Proyecto $proyecto, ProyectoRepository $proyectoRepository): Response
    {
        $oldEstado = $proyecto->getEstado();
        $form = $this->createForm(ProyectoType::class, $proyecto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if(
                $proyecto->getEstado() == Proyecto::PROYECTO_STATE['Terminado'] &&
                !$this->canCloseProject($proyecto, $proyectoRepository)
            ){
                $this->addFlash('error', 'Este proyecto tiene tareas incompletas y no se puede cerrar todavía');
                return $this->renderForm('proyecto/edit.html.twig', [
                    'proyecto' => $proyecto,
                    'form' => $form,
                ]);
            };

            $proyectoRepository->add($proyecto);

            if($oldEstado !== $proyecto->getEstado())
            {
                $event = new ProyectoEvent($proyecto);
                $this->eventDispatcher->addSubscriber(new ProyectoEventSubscriber($this->emailService));
                $this->eventDispatcher->dispatch($event, ProyectoEvent::NAME_CAMBIO_ESTADO);
            }

            return $this->redirectToRoute('app_proyecto_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('proyecto/edit.html.twig', [
            'proyecto' => $proyecto,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_proyecto_delete", methods={"POST"})
     */
    public function delete(Request $request, Proyecto $proyecto, ProyectoRepository $proyectoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$proyecto->getId(), $request->request->get('_token'))) {
            $proyectoRepository->remove($proyecto);
        }

        return $this->redirectToRoute('app_proyecto_index', [], Response::HTTP_SEE_OTHER);
    }

    private function canCloseProject(Proyecto $proyecto, ProyectoRepository $proyectoRepository)
    {
        $tareasPendientes = $proyectoRepository->getTareasPendientes($proyecto);

        foreach ($tareasPendientes as $value) {
            foreach ($value->getTareas() as $tarea) {
                if($tarea->getEstado() != Tarea::TAREA_STATE['Terminada']){
                    return false;
                }
            }
        }

        return true;
    }
}

templates/proyecto/_delete_form.html.twig
<form method="post" action="{{ path('app_proyecto_delete', {'id': proyecto.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ proyecto.id) }}">
    <button class="btn">Delete</button>
</form>

templates/proyecto/edit.html.twig
{% extends 'base/base.html.twig' %}

{% block body %}
    <h1>Edit Proyecto</h1>

    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="flash-{{ label }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}

    {{ include('proyecto/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_proyecto_index') }}">back to list</a>

    {{ include('proyecto/_delete_form.html.twig') }}
{% endblock %}

templates/proyecto/index.html.twig
{% extends 'base/base.html.twig' %}

{% block body %}
    {% include 'base/common-elements/details_title.html.twig' with {
        'title': 'Proyectos',
        'path': path('app_proyecto_new'),
        'button_text': 'Crear proyecto'
    } %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Fecha_entrega</th>
                <th>Estado</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for proyecto in proyectos %}
            <tr>
                <td>{{ proyecto.id }}</td>
                <td>{{ proyecto.fechaEntrega ? proyecto.fechaEntrega|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ proyecto.estado }}</td>
                <td>
                    <a href="{{ path('app_proyecto_show', {'id': proyecto.id}) }}">show</a>
                    <a href="{{ path('app_proyecto_edit', {'id': proyecto.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">{{ "no_records_found" | trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/proyecto/new.html.twig
{% extends 'base/base.html.twig' %}

{% block body %}
    <h1>Crear nuevo proyecto</h1>

    {{ include('proyecto/_form.html.twig') }}

    <a href="{{ path('app_proyecto_index') }}">back to list</a>
{% endblock %}

templates/proyecto/show.html.twig
{% extends 'base/base.html.twig' %}

{% block body %}
    <h1>Proyecto</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ proyecto.id }}</td>
            </tr>
            <tr>
                <th>Fecha_entrega</th>
                <td>{{ proyecto.fechaEntrega ? proyecto.fechaEntrega|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ proyecto.estado }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_proyecto_index') }}">back to list</a>

    <a href="{{ path('app_proyecto_edit', {'id': proyecto.id}) }}">edit</a>

    {{ include('proyecto/_delete_form.html.twig') }}
{% endblock %}