src/Entity/Presupuesto.php
<?php

namespace App\Entity;

use App\Repository\PresupuestoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PresupuestoRepository::class)
 */
class Presupuesto
{
    public const PRESUPUESTO_TYPES = [
        'Web' => 'web',
        'Mobile' => 'mobile',
        'Desktop' => 'desktop'
    ];

    public const PRESUPUESTO_STATES = [
        'Pendiente' => 'pendiente',
        'Aprobado' => 'aprobado',
        'Rechazado' => 'rechazado'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $tipo;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $estado;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $precio_final;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="presupuestos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity=Proyecto::class, mappedBy="presupuesto", cascade={"persist", "remove"})
     */
    private $proyecto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $descripcionProyecto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $correoContacto;

    public function __construct()
    {
        $this->estado = self::PRESUPUESTO_STATES['Pendiente'];
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTipo(): ?string
    {
        return $this->tipo;
    }

    public function setTipo(string $tipo): self
    {
        if(!in_array($tipo, $this::PRESUPUESTO_TYPES)){
            throw new Exception('Tipo de presupuesto no válido: '.$tipo);
        };

        $this->tipo = $tipo;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        if(!in_array($estado, $this::PRESUPUESTO_STATES)){
            throw new Exception('Estado del presupuesto de presupuesto no válido: '.$estado);
        };

        $this->estado = $estado;

        return $this;
    }

    public function getPrecioFinal(): ?float
    {
        return $this->precio_final;
    }

    public function setPrecioFinal(?float $precio_final): self
    {
        $this->precio_final = $precio_final;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProyecto(): ?Proyecto
    {
        return $this->proyecto;
    }

    public function setProyecto(Proyecto $proyecto): self
    {
        // set the owning side of the relation if necessary
        if ($proyecto->getPresupuesto() !== $this) {
            $proyecto->setPresupuesto($this);
        }

        $this->proyecto = $proyecto;

        return $this;
    }

    public function getDescripcionProyecto(): ?string
    {
        return $this->descripcionProyecto;
    }

    public function setDescripcionProyecto(string $descripcionProyecto): self
    {
        $this->descripcionProyecto = $descripcionProyecto;

        return $this;
    }

    public function getCorreoContacto(): ?string
    {
        return $this->correoContacto;
    }

    public function setCorreoContacto(string $correoContacto): self
    {
        $this->correoContacto = $correoContacto;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getId() ??'';
    }
}

src/Form/PresupuestoType.php
<?php

namespace App\Form;

use App\Entity\Presupuesto;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PresupuestoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('tipo', ChoiceType::class, [
                'label' => 'Tipo de proyecto',
                'choices'  => Presupuesto::PRESUPUESTO_TYPES
            ])
            ->add('correoContacto', EmailType::class, [
                'label' => 'Correo de Contacto',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('descripcionProyecto', TextareaType::class, [
                'label' => 'Descripción del Proyecto',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('user')
        ;

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            /** @var var Presupuesto $presupuesto */
            $presupuesto = $event->getData();
            $form = $event->getForm();

            if(null !== $presupuesto->getId()) {
                $form->add('estado', ChoiceType::class, [
                        'choices'  => Presupuesto::PRESUPUESTO_STATES,
                        'label' => 'Status',
                    ]);
                $form->add('precio_final', NumberType::class, [
                    'label' => 'Precio Final',
                ]);
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Presupuesto::class,
        ]);
    }
}

src/Controller/PresupuestoController.php
<?php

namespace App\Controller;

use App\Entity\Presupuesto;
use App\Event\Presupuesto\PresupuestoAprobadoEvent;
use App\Event\Presupuesto\PresupuestoSolicitadoEvent;
use App\EventSubscriber\PresupuestoEventSubscriber;
use App\Form\PresupuestoType;
use App\Repository\PresupuestoRepository;
use App\Services\EmailService;
use Psr\EventDispatcher\EventDispatcherInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/presupuesto")
 */
class PresupuestoController extends AbstractController
{
    private EventDispatcherInterface $eventDispatcher;
    private EmailService $emailService;
    private TranslatorInterface $translator;

    public function __construct(
        EventDispatcherInterface $eventDispatcher,
        EmailService $emailService,
        TranslatorInterface $translator
    )
    {
        $this->eventDispatcher = $eventDispatcher;
        $this->emailService = $emailService;
        $this->translator = $translator;
    }


    /**
     * @Route("/", name="app_presupuesto_index", methods={"GET"})
     * @Security("is_granted('ROLE_COMERCIAL')")
     */
    public function index(PresupuestoRepository $presupuestoRepository): Response
    {
        return $this->render('presupuesto/index.html.twig', [
            'presupuestos' => $presupuestoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_presupuesto_new", methods={"GET", "POST"})
     */
    public function new(Request $request, PresupuestoRepository $presupuestoRepository): Response
    {
        $presupuesto = new Presupuesto();
        $form = $this->createForm(PresupuestoType::class, $presupuesto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            try {
                $presupuestoRepository->add($presupuesto);
                $event = new PresupuestoSolicitadoEvent($presupuesto);
                $this->eventDispatcher->dispatch($event, PresupuestoSolicitadoEvent::NAME);
                $this->addFlash('success',$this->translator->trans('flash.success.create_budget'));

                return $this->redirectToRoute('index', [], Response::HTTP_SEE_OTHER);
            }catch (\Exception $exception) {
                $this->addFlash('danger',$this->translator->trans('flash.error.create_budget'));
            }
        }

        return $this->renderForm('presupuesto/new.html.twig', [
            'presupuesto' => $presupuesto,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_presupuesto_show", methods={"GET"})
     * @Security("is_granted('ROLE_COMERCIAL')")
     */
    public function show(Presupuesto $presupuesto): Response
    {
        return $this->render('presupuesto/show.html.twig', [
            'presupuesto' => $presupuesto,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_presupuesto_edit", methods={"GET", "POST"})
     * @Security("is_granted('ROLE_COMERCIAL')")
     */
    public function edit(Request $request, Presupuesto $presupuesto, PresupuestoRepository $presupuestoRepository): Response
    {
        $form = $this->createForm(PresupuestoType::class, $presupuesto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $presupuestoRepository->add($presupuesto);

                if($presupuesto->getEstado() === Presupuesto::PRESUPUESTO_STATES['Aprobado'])
                {
                    $event = new PresupuestoAprobadoEvent($presupuesto);
                    $this->eventDispatcher->dispatch($event, PresupuestoAprobadoEvent::NAME);
                }

                $this->addFlash('success',$this->translator->trans('flash.edit_budget.success'));
                return $this->redirectToRoute('app_presupuesto_index', [], Response::HTTP_SEE_OTHER);

            }
            catch (\Exception $ex) {
                $this->addFlash('danger',$this->translator->trans('flash.edit_budget.error'));
            }
        }

        return $this->renderForm('presupuesto/edit.html.twig', [
            'presupuesto' => $presupuesto,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_presupuesto_delete", methods={"POST"})
     * @Security("is_granted('ROLE_COMERCIAL')")
     */
    public function delete(Request $request, Presupuesto $presupuesto, PresupuestoRepository $presupuestoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$presupuesto->getId(), $request->request->get('_token'))) {
            $presupuestoRepository->remove($presupuesto);
        }

        $this->addFlash('success',$this->translator->trans('flash.delete_budget.success'));

        return $this->redirectToRoute('app_presupuesto_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * Esqueleto del controlador de presupuesto
     * Creado para iniciar los siguiente eventos:
     *  - 1) al crear un presupuesto: 'onPresupuestoSolicitado'
     *      - Llama al método o métodos de envío de correo definidos en los servicios del ejercicio 8.2
     *  - 2) 'onPresupuestoAprobado'
     *      - Llame al método o métodos de envío de correo definidos en los servicios del ejercicio 8.2
     */

    /*
     * Método de creación de presupuesto
     */
    public function nuevo(Request $request, EventDispatcherInterface $dispatcher) : Response
    {
        // TODO: Definición lógica de creación de presupuesto (Form, Api...)
        $presupuesto = ['id' => 1];

        // Cuando acaba correctamente la lógica de aprobación de un presupuesto se dispara el un
        // new PresupuestoSolicitadoEvent
        $event = new PresupuestoSolicitadoEvent($presupuesto);
        $dispatcher->dispatch($event, $event::NAME);

        return $this->json('Presupuesto solicitado ');
    }

    /*
     * Método de aprobación de presupuesto
     */
    public function aprobar(Request $request, EventDispatcherInterface $dispatcher) : Response
    {
        // TODO: Definición lógica de creación de presupuesto (Form, Api...)
        $presupuesto = ['id' => 1];

        // Cuando acaba correctamente la lógica de aprobación de un presupuesto se dispara el un
        // new PresupuestoAprobadoEvent
        $event = new PresupuestoAprobadoEvent($presupuesto);
        $dispatcher->dispatch($event, $event::NAME);

        return $this->json('Presupuesto aprobado');
    }
}

templates/presupuesto/_delete_form.html.twig
<form method="post" action="{{ path('app_presupuesto_delete', {'id': presupuesto.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ presupuesto.id) }}">
    <button class="btn">Delete</button>
</form>

templates/presupuesto/_form.html.twig
<div class="card mt-5">
    <div class="card-body">
        {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
            <div class="text-center">
                <p>Estás a punto de crear un nuevo presupuesto.</p>
                <p>El procedimiento estándar incluye la validación de los datos y avanzar paso a paso hasta la creación del proyecto.</p>
                <p>En cada paso del proceso, serás informado por correo electrónico.</p>
            </div>
        {% endif %}

        {{ form_start(form) }}
            {{ form_widget(form) }}
        <button type="button" class="btn btn-secondary btn-block" id="showPriceButton">Muestra el precio aproximado</button>
        <button type="submit" class="btn btn-primary btn-block">{{ button_label|default('Save') }}</button>
        {{ form_end(form) }}

        <!-- Card -->
        <div class="card mt-3 mx-auto" id="priceCard">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="mb-0">Precio aproximado</h5>
                <button type="button" class="close" id="closePriceCard" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted" id="priceCardField">Card subtitle</h6>
                <p class="card-text" id="priceCardText">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>
</div>

templates/presupuesto/base_presupuesto.html.twig
{% extends 'base/base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('js_presupuesto') }}
{% endblock %}

templates/presupuesto/edit.html.twig
{% extends 'presupuesto/base_presupuesto.html.twig' %}

{% block body %}
    {% include 'base/common-elements/details_title.html.twig' with {
        'title': 'Editar presupuesto',
        'path': '',
        'button_text': ''
    } %}

    {{ include('presupuesto/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="d-flex flex-row align-items-center mt-3">
        <a href="{{ path('app_presupuesto_index') }}" class="btn btn-secondary mr-2">Volver al listado</a>
        {{ include('presupuesto/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/presupuesto/index.html.twig
{% extends 'presupuesto/base_presupuesto.html.twig' %}

{% block body %}
    {% include 'base/common-elements/details_title.html.twig' with {
        'title': 'Presupuestos',
        'path': path('app_presupuesto_new'),
        'button_text': 'Crear presupuesto'
    } %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Tipo</th>
                <th>Estado</th>
                <th>Precio final</th>
                <th>Descripción Cliente</th>
                <th>Contacto</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for presupuesto in presupuestos %}
            <tr>
                <td>{{ presupuesto.id }}</td>
                <td>{{ presupuesto.tipo }}</td>
                <td>{{ presupuesto.estado }}</td>
                <td>{{ presupuesto.precioFinal }}</td>
                <td>{{ presupuesto.descripcionProyecto }}</td>
                <td>{{ presupuesto.correoContacto }}</td>
                <td>
                    <a href="{{ path('app_presupuesto_show', {'id': presupuesto.id}) }}" class="btn btn-secondary mr-2">{{ "Show" | trans }}</a>
                    <a href="{{ path('app_presupuesto_edit', {'id': presupuesto.id}) }}" class="btn btn-secondary mr-2 {{ presupuesto.estado == 'aprobado' ? 'disabled-link' : '' }}">{{ "Edit" | trans }}</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">{{ "no_records_found" | trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/presupuesto/new.html.twig
{% extends 'presupuesto/base_presupuesto.html.twig' %}

{% block body %}
    {% include 'base/common-elements/details_title.html.twig' with {
        'title': 'Solicitar un presupuesto',
        'path': '',
        'button_text': ''
    } %}

    {{ include('presupuesto/_form.html.twig') }}

    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
        <div class="d-flex flex-row align-items-center mt-3">
            <a href="{{ path('app_presupuesto_index') }}" class="btn btn-secondary mr-2">Volver al listado</a>
        </div>
    {% endif %}

{% endblock %}

templates/presupuesto/show.html.twig
{% extends 'presupuesto/base_presupuesto.html.twig' %}

{% block body %}
    <h1>Presupuesto</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ presupuesto.id }}</td>
            </tr>
            <tr>
                <th>Tipo</th>
                <td>{{ presupuesto.tipo }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ presupuesto.estado }}</td>
            </tr>
            <tr>
                <th>Precio_final</th>
                <td>{{ presupuesto.precioFinal }}</td>
            </tr>
        </tbody>
    </table>

    <div class="d-flex flex-row align-items-center mb-3">
        <a href="{{ path('app_presupuesto_index') }}" class="btn btn-secondary mr-2">{{ 'Back to the list' | trans }}</a>
        {% if presupuesto.estado != 'aprobado' %}
            <a href="{{ path('app_presupuesto_edit', {'id': presupuesto.id}) }}" class="btn btn-primary mr-2">{{ 'Edit' | trans }}</a>
        {% endif %}

        {{ include('presupuesto/_delete_form.html.twig') }}
    </div>
{% endblock %}